### ISSUE TITLE
Just some thoughts

### ISSUE THREAD

**Issue by selimfirat** [cagdass/bitcoin-price-search-popularity#1]
Hi
I really liked this repository. To practice data processing, I will implement percent change graph based on same variables and will also create pull request. (Probably ~12 days later)

Do you have any other ideas to improve this repository?

**Comment by cagdass** [comment]
No immediate ideas from me, but would love a collaborator <3

**Comment by selimfirat** [comment]
Perfect :yum:
Let's make this repository great
